---
name: "build"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

permissions:
  attestations: write
  id-token: write
  contents: write

jobs:
  build:
    name: build-${{ matrix.toolchain }}-${{ matrix.version }}
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          # - gkdpixel deprecated, but also i386 only so it won't build without buildx
          - m17 # (deprecated)
          - magicmini
          - miyoomini # (deprecated)
          - my282
          - my355
          - rg35xx # (deprecated)
          - rg35xxplus
          - rgb30 # (deprecated)
          # - tg3040 now merged with tg5040, so we can't build it separately
          - tg5040
          - trimuismart # (deprecated)
          - zero28
        version:
          - v20250126-0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone the union repository
        run: |
          git clone https://github.com/shauninman/union-${{ matrix.toolchain }}-toolchain
          cd union-${{ matrix.toolchain }}-toolchain
          git checkout ${{ matrix.version }}

      - name: Upload the toolchain
        uses: docker/build-push-action@v3
        with:
          context: union-${{ matrix.toolchain }}-toolchain
          file: Dockerfile
          tags: savant/minui-toolchain:${{ matrix.toolchain }}-${{ matrix.version }}
          push: true
          platforms: linux/arm64
